# https://github.com/actions/github-script

name: Create PR (Staging, Main)
on:
  pull_request:
    types:
      - opened
    branches:
      - alpha

jobs:
  create-staging-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Github Object
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/scripts/create-pr.js')
            customForFitpet = { base: 'staging' }
            await script({ context, github }, customForFitpet)
  create-main-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Github Object
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/scripts/create-pr.js')
            customForFitpet = { base: 'main' }
            await script({ context, github }, customForFitpet)
